name: "test issue copy"
on:
    issue_comment:
        types: [created]
jobs:
    copy:
        runs-on: ubuntu-latest
        steps:
            - uses: soichisumi/issue-copy-action@v0.2.0
            - uses: actions/checkout@v1
            - uses: ./
              with:
                keyword: "/copy"
                targetRepository: the-collab-lab/smart-shopping-list
                githubToken: ${{ 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 }}
                contentOfNewIssue: 'prefix of newly created issue'
                
